Create Blob instead of crashing on binary data on deserialize
scimma/hop-client pull request #198
Opened 2023-01-07 02:09 UTC by alchzh

## Description

Currently, reading a message that has binary data without the proper deserialize plugin throws a UnicodeDecodeError exception.

I think the expected behavior is to create a Blob with the bytes.

This PR ignores any UnicodeDecodeErrors alongside JSONDecodeErrors

## Checklist

* [ ] All new functions and classes are documented and adhere to Google doc style (3.8.3-3.8.6 of [this](http://google.github.io/styleguide/pyguide.html#383-functions-and-methods) document)
* [ ] Add/update sphinx documentation with any relevant changes.
* [ ] Add/update pytest-style tests in `/tests`, ensuring sufficient code coverage.
* [ ] `make test` runs without errors.
* [ ] `make lint` doesn't give any warnings.
* [ ] `make format` doesn't give any code formatting suggestions.
* [ ] `make doc` runs without errors and generated docs render correctly.
* [ ] Check that CI pipeline run on this PR passes all stages.
* [ ] Review signoff by at least one developer.

NOTE: If this PR relates to a release, open and reference an issue with the Release checklist template.

2023-01-07 08:21 UTC, alchzh commented
I've corrected the test case that let this slip through (\x00 is valid unicode decodable)

It seems like a lint and format is required, but not because of this change.

2023-01-07 14:29 UTC, cnweaver requested changes
Thanks for catching this bug, and providing a nice fix and updated test. 

Sorry about the mess with the linter; I keep forgetting to fix that because I don't want to mix it with other changes. I've been kicking the can down the road by checking that the linter doesn't produce _new_ complaints, however, I will get this cleaned up ASAP.

2023-01-07 14:29 UTC, cnweaver commented on hop/io.py
> +        except (UnicodeDecodeError, json.JSONDecodeError):  # if we can't tell what the data is, pass it on unchanged
The linter becomes unhappy about the length of this line; the comment can just be moved down onto a line of its own to fix that.

2023-01-07 15:40 UTC, cnweaver approved these changes

2023-01-07 15:40 UTC, merged

2023-01-11 05:28 UTC, alchzh commented
Found out that on Python 3.6+ `json.loads` accepts `bytes` as an argument anyway, so we can just skip the `.decode()` and second exception type entirely.

It only makes a difference if the json isn't encoded as `utf-8` (see the encoding detector here https://github.com/python/cpython/blob/3.11/Lib/json/__init__.py#L244)